### ISSUE TITLE
Upload Image

### ISSUE THREAD

**Issue by sana-shrikant** [cs130-w21/2#13]
## User Story
As a user, I would like to upload images so that see where I have been on the trip so far.

## Detailed Description
Provide additional details and context.

## Acceptance Criteria
- [x] Given **[Condition]**, then **[Expected Result]**
- [x] Given **[Condition]**, then **[Expected Result]**
- [x] Given **[Condition]**, then **[Expected Result]**

**Comment by 2017jstone** [comment]
User can upload images in the ImageViewActivity
