### ISSUE TITLE
Store Notes in Database

### ISSUE THREAD

**Issue by DrewCaylor** [cs130-w21/2#53]
## User Story
As a User, I would like my notes to be stored in a database so that they can be accessed later.

## Detailed Description
Provide additional details and context.

## Acceptance Criteria
- [ ] When note is created, note will be stored in the database

**Comment by jasonpanelli** [comment]
Is this duplicate of #55 which is part of #6 story

**Comment by jasonpanelli** [comment]
Closed #55, use this issue instead

**Comment by jasonpanelli** [comment]
Closely associated with #7 and #8
