### ISSUE TITLE
Associate note with location

### ISSUE THREAD

**Issue by DrewCaylor** [cs130-w21/2#7]
## User Story
As a user, I would like to be able to associate a note with a location so that notes from each location are grouped and organized.

## Detailed Description
Provide additional details and context.

## Acceptance Criteria
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**

**Comment by jasonpanelli** [comment]
Replace with #53 and #62
