### ISSUE TITLE
Sort Notes by location or date

### ISSUE THREAD

**Issue by DrewCaylor** [cs130-w21/2#8]
## User Story
As a user, I would like to be able to sort my notes by location or date so that I can easily find them.

## Detailed Description
Provide additional details and context.

## Acceptance Criteria

- [ ] - If a location is selected only notes associated with this location will be displayed.

- [ ] - If a date is selected only notes created on this date will be displayed.

**Comment by jasonpanelli** [comment]
Replaced with #62
